### ISSUE TITLE
"error" in training - AttributeError: 'CastOutputToFloat' object has no attribute 'weight', RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by GreenTeaBD** [lxe/simple-llama-finetuner#29]
WSL2 Ubuntu, new install, I get the following error after it downloads the weights and tries to train.
Sorry I can't give more details, but I'm really not sure what's going on.

Traceback (most recent call last):
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/home/ckg/github/simple-llama-finetuner/main.py", line 166, in tokenize_and_train
    model = peft.get_peft_model(model, peft.LoraConfig(
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/mapping.py", line 147, in get_peft_model
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/peft_model.py", line 514, in __init__
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/peft_model.py", line 79, in __init__
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 118, in __init__
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 181, in _find_and_replace
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 196, in _replace_module
  File "/home/ckg/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1632, in __setattr__
    self.register_parameter(name, value)
  File "/home/ckg/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 108, in register_empty_parameter
    module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
  File "/home/ckg/.local/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 151, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
Number of samples: 534
Traceback (most recent call last):
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ckg/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ckg/.local/lib/python3.10/site-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/home/ckg/github/simple-llama-finetuner/main.py", line 164, in tokenize_and_train
    model = peft.prepare_model_for_int8_training(model)
  File "/home/ckg/.local/lib/python3.10/site-packages/peft/utils/other.py", line 72, in prepare_model_for_int8_training
  File "/home/ckg/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CastOutputToFloat' object has no attribute 'weight'

**Comment by lxe** [comment]
What hardware are you running on? Any other console traceback?

**Comment by GreenTeaBD** [comment]
Windows 11 (but in WSL2), otherwise working WSL install for diffusers and GPT-Neo finetuning (but, in their own environments)
A 5900x, 32GB ram, 100GB swap for WSL2 (I needed a lot for GPT-Neo stuff), and a 4090 for the gpu.

Nothing else to the traceback, everything else in the console is, what I think is, just normal stuff before
(llama-finetuner) ckg@Ryzen9:~/github/simple-llama-finetuner$ python main.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/ckg/anaconda3/envs/llama-finetuner/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ckg/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading base model...
Loading base model...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.

**Comment by GreenTeaBD** [comment]
Also, quick question that doesn't need its own issue. What's the significance of the 2 empty spaces in between each entry in the training data?

I had finetuned GPT-Neo a bunch, and I'm trying to wrap my head around the differences. And I haven't been able to find out if finetuning LLaMA uses <|endoftext|> tokens or not, or if there's another way to do it. Is that what the two empty lines are adding?

**Comment by lxe** [comment]
> Also, quick question that doesn't need its own issue. What's the significance of the 2 empty spaces in between each entry in the training data?

If you want to have newlines or empty lines in each of your samples, it helps. It's just the easiest way to format samples.

**Comment by lxe** [comment]
I just rewrote the whole thing. Still seeing the issue?
